tl-its-umich-edu/StudentDashboard

UI/js/controllers.js
UI/js/filters.js
UI/js/utils.js
UI/views/courses.html
server/courselist.rb
server/data_provider_esb.rb
server/data_provider_file.rb
server/local/studentdashboard-DEV.yml
server/local/studentdashboard-LOCALHOST.yml
server/local/studentdashboard-PROD.yml
server/local/studentdashboard-QA-LOAD-TEST.yml
server/local/studentdashboard-QA-NOAUTH.yml
server/local/studentdashboard-QA.yml
server/poll_esb.rb
server/spec/test_WAPI.rb
server/spec/test_WAPI_result_wrapper.rb
server/spec/test_courselist.rb
server/spec/test_data_provider_file.rb
server/spec/test_integration_WAPI.rb
server/spec/test_integration_data_provider_esb.rb
server/spec/test_stopwatch.rb
server/test-files/courses/gsilver.2010.json
server/test-files/courses/gsilver.2020.json
server/test-files/courses/meta404.json
server/test-files/courses/unitTestA.json
server/test-files/terms/default.json
server/test-files/terms/gsilver.json
server/test-files/terms/unitTestA.json

It is not necessary to review the tests, though you are welcome to do so.

Tlportal 174 - look up term data instead of using a static list.

---

server/local/configuration.mapping

TLPORTAL-186: fix typo in configuration.mapping

---

UI/js/controllers.js
UI/views/courses.html

for
https://jira.it.umich.edu/browse/TLPORTAL-189

Tlportal 189

---

UI/js/controllers.js
UI/views/courses.html
server/test-files/courses/test-instructors-roles.json

https://jira.it.umich.edu/browse/TLPORTAL-183

TLPORTAL-183 - sort faculty by order of importance

---

UI/js/controllers.js
UI/views/courses.html
server/data_provider_esb.rb
server/spec/test_integration_data_provider_esb.rb

for 
https://jira.it.umich.edu/browse/TLPORTAL-192

Tlportal 185

---

UI/css/custom_style.css
UI/index.erb
UI/views/courses.html
server/local/strings.yml

for 
https://jira.it.umich.edu/browse/TLPORTAL-192

TLPORTAL-192 - late breking changes to the ui

---

server/courselist.rb

Adding comment for clarification of default values.

TLPORTAL-175: document default values vs configuration

---

UI/index.erb

A new release candidate (RC4) based on RC2 should be created from based on this and the change should be merged into master as well.

TLPORTAL-210: fix IE 10 compatability issue

---

build.sh

Create copy of war with name "portal" to provide more agnostic user facing URL.

TLPORTAL-211: add portal.war version

---

UI/js/controllers/controllers.js
UI/views/courses.html

Merge to LATTE_2.0 from gsilver TLPORTAL-309

TLPORTAL-309 - display error message (was added to the wrong scope)

---

UI/views/courses.html
server/courselist.rb
server/spec/test_app_external_resources.rb
server/spec/test_external_resources_file.rb
server/test-files/resources/text/1.txt

Commit fixes for LATTE_2.0 branch: TLPORTAL-315, TLPORTAL-36, TLPORTAL-321

Latte 2.0 TLPORTAL-315, TLPORTAL-36, TLPORTAL-321

---

server/local/studentdashboard-DEV.yml

Not reviewed since required for testing install and non-production configuration.

TLPORTAL-360: update studentdashboard.yml for DEV instance 

---

tools/build.sh

TLPORTAL-366 rename build file to VERSION.Makefile

---

Gemfile
Gemfile.lock
UI/views/status.html.erb
UI/views/status.json.erb
server/courselist.rb
server/spec/test_app_status_urls.rb
tools/build.sh

Add status url space Dashboard to reveal build information and the ping and check urls.

TLPORTAL-252: add status urls

---

UI/js/controllers/controllers.js
UI/js/filters/filters.js
UI/js/utils/utils.js

for
https://itsjira.umms.med.umich.edu/browse/TLPORTAL-389

TLPORTAL-389 - tweak to decide if an item is due today

---

UI/js/factories/factories.js
UI/js/filters/filters.js
UI/views/courses.html

for https://jira.it.umich.edu/browse/TLPORTAL-392

Tlportal 392

---

UI/views/schedule.html

for
https://itsjira.umms.med.umich.edu/browse/TLPORTAL-403

TLPORTAL-403 - remove debug footer from schedule panel

---

UI/views/courses.html

for second pass at TLPORTAL-388

TLPORTAL-388-2 - change message and add a toggle for meetings

---

server/local/studentdashboard-DEV.yml
server/local/studentdashboard-LOCALHOST.yml
server/local/studentdashboard-PROD.yml
server/local/studentdashboard-QA-LOAD-TEST.yml
server/local/studentdashboard-QA.yml
server/local/studentdashboard.yml.TXT

See:
https://itsjira.umms.med.umich.edu/browse/TLPORTAL-400

TLPORTAL-400 - spruce up configuration yml

---

UI/data/courses/ralt.json
UI/data/terms.json
UI/data/todolms/ralt.json
UI/index.erb
UI/js/controllers/controllers.js
UI/js/utils/utils.js
UI/views/schedule.html

Add the Canvas course names to the Schedule panel. Use the existing CTools course names. This will show in the links below the assignments as "Go to course site for _Course-Name_"

Tlportal 417

---

UI/js/controllers/controllers.js
UI/js/factories/factories.js
UI/js/utils/utils.js
UI/views/schedule.html

- will need to do some refactoring later, this just so that we can take a look at the performance for now.

TLPORTAL-423 - request all parts of the schedule in parallel

---

tools/README.md
tools/data/Dash-Externals.html
tools/data/formatJson.pl
tools/data/getDashLogs.sh
tools/data/parseLogs.pl

Revised based on testing comments.

Tlportal 415

---

UI/js/utils/utils.js

Re: https://jira.it.umich.edu/browse/TLPORTAL-424

TLPORTAL-424-2 - adjust what days in the past get shown

---

server/courselist.rb
server/data_provider_canvas_esb.rb
server/spec/test_data_provider_canvas_esb.rb
server/spec/test_integration_WAPI_CANVAS.rb

Get canvas course assignments from each listed course individually to avoid losing all data due to issues with particular courses.

Tlportal 456 - get assignments from Canvas course by course

---

tools/build.sh

Make sure that the version of the bundler tools is consistent across development and production environments.

TLPORTAL-378: add specific bundler version.

---

server/courselist.rb
server/spec/test_courselist.rb

Ensure that html_escaping will not turn a nil value into an empty string.

TLPORTAL-451: global fix for html escape issue

---

server/local/configuration.mapping

Tlportal 447 - update configuration.mapping

---

server/canvas_api_response.rb
server/data_provider.rb

Tlportal 461 - refactor data provider to reduce repetition and make configuration 

---

server/local/studentdashboard-PROD.yml
server/local/studentdashboard-QA.yml

TLPSO-428: update configuration files
